global_costmap:
  global_costmap:
    ros__parameters:
      robot_radius: 2.0
      plugins: ["static_layer", "inflation_layer"]
      use_sim_time: false
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 5.0

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    use_sim_time: False
    GridBased:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      downsample_costmap: false
      downsampling_factor: 1
      tolerance: 0.25
      allow_unknown: true
      max_iterations: 1000000
      max_on_approach_iterations: 1000
      max_planning_time: 1.0
      motion_model_for_search: "DUBIN"
      min_turning_radius: 20.0
      smooth_path: true

controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["goal_checker"]
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: false
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 15.0
      lookahead_dist: 18.0
      use_velocity_scaled_lookahead_dist: false
      use_collision_detection: false
      use_regulated_linear_velocity_scaling: false
      use_cost_regulated_linear_velocity_scaling: false
      use_fixed_curvature_lookahead: false
      use_rotate_to_heading: false
      allow_reversing: false
      use_cancel_deceleration: false
      interpolate_curvature_after_goal: false